//
//  CitiesPresenterTests.swift
//  Quality Of Life
//
//  Created by Dan Mori on 06/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Quality_Of_Life
import XCTest

class CitiesPresenterTests: XCTestCase {
    var sut: CitiesPresenter!
    
    override func setUp() {
        super.setUp()
        setupCitiesPresenter()
    }
  
    override func tearDown() {
        super.tearDown()
    }

    func setupCitiesPresenter() {
        sut = CitiesPresenter()
    }
  
  // MARK: Test doubles
  
    class CitiesDisplayLogicSpy: CitiesDisplayLogic {
        var displayCitiesCalled = false
        func displayCities(viewModel: Cities.GetCities.ViewModel) {
            displayCitiesCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentCities() {
        let spy = CitiesDisplayLogicSpy()
        sut.viewController = spy
        let response = Cities.GetCities.Response(cities: [])
        
        sut.presentCities(response: response)
        
        XCTAssertTrue(spy.displayCitiesCalled, "presentCities should ask the viewcontroller to display the result")
    }
}
