//
//  CitiesInteractorTests.swift
//  Quality Of Life
//
//  Created by Dan Mori on 06/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Quality_Of_Life
import XCTest

class CitiesInteractorTests: XCTestCase {
    var sut: CitiesInteractor!
    lazy var service: ServiceProvider = TestServiceAPI()
    
    override func setUp() {
        super.setUp()
        setupCitiesInteractor()
    }
  
    override func tearDown() {
        super.tearDown()
    }
  
  // MARK: Test setup
  
  func setupCitiesInteractor()
  {
      sut = CitiesInteractor(withServiceProvider: service)
  }
  
  // MARK: Test doubles
  
    class CitiesPresentationLogicSpy: CitiesPresentationLogic {
        var presentCitiesCalled = false
        func presentCities(response: Cities.GetCities.Response) {
            presentCitiesCalled = true
        }
    }
  
  // MARK: Tests
    
    func testGetCities() {
        let spy = CitiesPresentationLogicSpy()
        sut.presenter = spy
        let request = Cities.GetCities.Request()
        
        sut.getCities(request: request)
        
        XCTAssertTrue(spy.presentCitiesCalled, "getCities should ask for the presenter to format the result.")
    }

}
