//
//  CitiesPresenter.swift
//  Quality Of Life
//
//  Created by Dan Mori on 05/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CitiesPresentationLogic {
    func presentCities(response: Cities.GetCities.Response)
    func presentCityDetails(response: Cities.ShowCityDetails.Response)
}

class CitiesPresenter: CitiesPresentationLogic {
    weak var viewController: CitiesDisplayLogic?

    func presentCities(response: Cities.GetCities.Response) {
        viewController?.displayCities(viewModel: Cities.GetCities.ViewModel(cities: response.cities))
    }
    
    func presentCityDetails(response: Cities.ShowCityDetails.Response) {
        viewController?.displayCityDetails(viewModel: Cities.ShowCityDetails.ViewModel())
    }
}
