//
//  CitiesInteractor.swift
//  Quality Of Life
//
//  Created by Dan Mori on 05/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CitiesBusinessLogic {
    func getCities(request: Cities.GetCities.Request)
}

protocol CitiesDataStore {
    var cities: [CityItem] { get set }
}

class CitiesInteractor: CitiesBusinessLogic, CitiesDataStore {
    var presenter: CitiesPresentationLogic?
    var worker: CitiesWorker?
    var cities: [CityItem] = []
    
    func getCities(request: Cities.GetCities.Request) {
        ServiceAPI().getMostPopulatedCities {
            switch $0 {
            case .failure(_):
                print("falhou")
            case let .success(citiesResponse):
                let response = Cities.GetCities.Response(cities: citiesResponse.cities)
                self.presenter?.presentCities(response: response)
            }
        }
    }
}
