//
//  CitiesModels.swift
//  Quality Of Life
//
//  Created by Dan Mori on 05/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Cities {
    enum GetCities {
        struct Request {}
        struct Response {
            let cities: [City]
        }
        struct ViewModel {
            let cities: [City]
        }
    }
    enum ShowCityDetails {
        struct Request{
            let cityIndex: Int
        }
        struct Response {}
        struct ViewModel {}
    }
}
