//
//  CitiesInteractor.swift
//  Quality Of Life
//
//  Created by Dan Mori on 05/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CitiesBusinessLogic
{
  func doSomething(request: Cities.Something.Request)
}

protocol CitiesDataStore
{
  //var name: String { get set }
}

class CitiesInteractor: CitiesBusinessLogic, CitiesDataStore
{
  var presenter: CitiesPresentationLogic?
  var worker: CitiesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Cities.Something.Request)
  {
    worker = CitiesWorker()
    worker?.doSomeWork()
    
    let response = Cities.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
