//
//  CitiesRouter.swift
//  Quality Of Life
//
//  Created by Dan Mori on 05/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CitiesRoutingLogic {
    func routeToCityDetails()
}

protocol CitiesDataPassing
{
  var dataStore: CitiesDataStore? { get }
}

class CitiesRouter: NSObject, CitiesRoutingLogic, CitiesDataPassing {
    weak var viewController: CitiesViewController?
    var dataStore: CitiesDataStore?
    
    func routeToCityDetails() {
        let destinationVC = CityDetailsViewController()
        var destionationDS = destinationVC.router!.dataStore!
        passDataToCityDetails(source: dataStore!, destination: &destionationDS)
        navigateToCityDetails(source: viewController!, destination: destinationVC)
    }
    
    func passDataToCityDetails(source: CitiesDataStore, destination: inout CityDetailsDataStore) {
        destination.cityId = source.cityId
    }
    
    func navigateToCityDetails(source: CitiesViewController, destination: CityDetailsViewController) {
        source.show(destination, sender: nil)
    }
}
