//
//  CitiesPresenter.swift
//  Quality Of Life
//
//  Created by Dan Mori on 05/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CitiesPresentationLogic
{
  func presentSomething(response: Cities.Something.Response)
}

class CitiesPresenter: CitiesPresentationLogic
{
  weak var viewController: CitiesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Cities.Something.Response)
  {
    let viewModel = Cities.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
