//
//  CityDetailsInteractor.swift
//  Quality Of Life
//
//  Created by Dan Mori on 06/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityDetailsBusinessLogic
{
  func doSomething(request: CityDetails.Something.Request)
}

protocol CityDetailsDataStore
{
  var cityId: String { get set }
}

class CityDetailsInteractor: CityDetailsBusinessLogic, CityDetailsDataStore
{
  var presenter: CityDetailsPresentationLogic?
  var worker: CityDetailsWorker?
  var cityId: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CityDetails.Something.Request)
  {
    worker = CityDetailsWorker()
//    worker?.doSomeWork()
    
    let response = CityDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
