//
//  CityDetailsPresenter.swift
//  Quality Of Life
//
//  Created by Dan Mori on 06/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityDetailsPresentationLogic {
    func presentCityDetails(response: CityDetails.LoadCityDetails.Response)
}

class CityDetailsPresenter: CityDetailsPresentationLogic {
    weak var viewController: CityDetailsDisplayLogic?
    
    func presentCityDetails(response: CityDetails.LoadCityDetails.Response) {
        let population = response.population.formattedWithSeparator
        
        let viewModel = CityDetails.LoadCityDetails.ViewModel(name: response.name, fullName: response.fullName, population: population)
        viewController?.displayCityDetails(viewModel: viewModel)
    }
}
