//
//  CityDetailsPresenter.swift
//  Quality Of Life
//
//  Created by Dan Mori on 06/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityDetailsPresentationLogic {
    func presentSomething(response: CityDetails.Something.Response)
}

class CityDetailsPresenter: CityDetailsPresentationLogic {
    weak var viewController: CityDetailsDisplayLogic?
  
  func presentSomething(response: CityDetails.Something.Response)
  {
    let viewModel = CityDetails.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
